[2023-07-17 09:57:15,506] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2023-07-13T00:00:00+00:00 [queued]>
[2023-07-17 09:57:15,512] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2023-07-13T00:00:00+00:00 [queued]>
[2023-07-17 09:57:15,513] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 09:57:15,513] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-17 09:57:15,513] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 09:57:15,533] {taskinstance.py:1377} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2023-07-13 00:00:00+00:00
[2023-07-17 09:57:15,535] {standard_task_runner.py:52} INFO - Started process 6664 to run task
[2023-07-17 09:57:15,539] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2023-07-13T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmprc8vsy9i', '--error-file', '/tmp/tmp19bcd3t1']
[2023-07-17 09:57:15,539] {standard_task_runner.py:80} INFO - Job 5: Subtask twitter_datascience
[2023-07-17 09:57:15,676] {task_command.py:370} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2023-07-13T00:00:00+00:00 [running]> on host ubuntu
[2023-07-17 09:57:15,773] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=TwitterDAG
AIRFLOW_CTX_TASK_ID=twitter_datascience
AIRFLOW_CTX_EXECUTION_DATE=2023-07-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-13T00:00:00+00:00
[2023-07-17 09:57:15,796] {base.py:68} INFO - Using connection ID 'twitter_default' for task execution.
[2023-07-17 09:57:15,808] {logging_mixin.py:115} WARNING - /home/eugenio/Documents/curso/venv/lib/python3.9/site-packages/airflow/models/connection.py:294 DeprecationWarning: Encountered non-JSON in `extra` field for connection 'twitter_default'. Support for non-JSON `extra` will be removed in Airflow 3.0
[2023-07-17 09:57:15,809] {connection.py:403} ERROR - Failed parsing the json for conn_id twitter_default
Traceback (most recent call last):
  File "/home/eugenio/Documents/curso/venv/lib/python3.9/site-packages/airflow/models/connection.py", line 400, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 143 (char 142)
[2023-07-17 09:57:15,813] {twitter_hook.py:34} INFO - URL: https://labdados.com/2/tweets/search/recent?query=datascience&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,lang,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2023-07-13T00:00:00.00Z&end_time=2023-07-14T00:00:00.00Z
[2023-07-17 09:57:16,228] {twitter_hook.py:34} INFO - URL: https://labdados.com/2/tweets/search/recent?query=datascience&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,lang,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2023-07-13T00:00:00.00Z&end_time=2023-07-14T00:00:00.00Z&next_token=1234567890abcdef
[2023-07-17 09:57:16,382] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=TwitterDAG, task_id=twitter_datascience, execution_date=20230713T000000, start_date=20230717T165715, end_date=20230717T165716
[2023-07-17 09:57:16,440] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-17 09:57:16,456] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
