[2023-07-17 09:57:11,802] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2023-07-12T00:00:00+00:00 [queued]>
[2023-07-17 09:57:11,807] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2023-07-12T00:00:00+00:00 [queued]>
[2023-07-17 09:57:11,807] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 09:57:11,807] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-17 09:57:11,807] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 09:57:11,818] {taskinstance.py:1377} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2023-07-12 00:00:00+00:00
[2023-07-17 09:57:11,820] {standard_task_runner.py:52} INFO - Started process 6597 to run task
[2023-07-17 09:57:11,827] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2023-07-12T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpo4c6lfvz', '--error-file', '/tmp/tmpcutor4q_']
[2023-07-17 09:57:11,828] {standard_task_runner.py:80} INFO - Job 4: Subtask twitter_datascience
[2023-07-17 09:57:11,867] {task_command.py:370} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2023-07-12T00:00:00+00:00 [running]> on host ubuntu
[2023-07-17 09:57:11,921] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=TwitterDAG
AIRFLOW_CTX_TASK_ID=twitter_datascience
AIRFLOW_CTX_EXECUTION_DATE=2023-07-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-12T00:00:00+00:00
[2023-07-17 09:57:11,927] {base.py:68} INFO - Using connection ID 'twitter_default' for task execution.
[2023-07-17 09:57:11,932] {logging_mixin.py:115} WARNING - /home/eugenio/Documents/curso/venv/lib/python3.9/site-packages/airflow/models/connection.py:294 DeprecationWarning: Encountered non-JSON in `extra` field for connection 'twitter_default'. Support for non-JSON `extra` will be removed in Airflow 3.0
[2023-07-17 09:57:11,932] {connection.py:403} ERROR - Failed parsing the json for conn_id twitter_default
Traceback (most recent call last):
  File "/home/eugenio/Documents/curso/venv/lib/python3.9/site-packages/airflow/models/connection.py", line 400, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 143 (char 142)
[2023-07-17 09:57:11,934] {twitter_hook.py:34} INFO - URL: https://labdados.com/2/tweets/search/recent?query=datascience&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,lang,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2023-07-12T00:00:00.00Z&end_time=2023-07-13T00:00:00.00Z
[2023-07-17 09:57:12,358] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=TwitterDAG, task_id=twitter_datascience, execution_date=20230712T000000, start_date=20230717T165711, end_date=20230717T165712
[2023-07-17 09:57:12,403] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-17 09:57:12,419] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
